Lesson 2 done
accountF/jet-start pull request #6
Opened 2020-03-08 23:24 UTC by accountF

2020-03-09 07:56 UTC, Zwillinge requested changes

2020-03-09 07:56 UTC, Zwillinge commented on sources/views/contacts/formInContacts.js
> +					options:[{value:1}, {value:2}, {value:3}]},
country and statuses combo boxes need to reflect statuses and countries data from models and have the correct templates for suggest body to show the values, not ids

2020-03-09 07:56 UTC, Zwillinge commented on sources/views/contacts/formInContacts.js
> +			contacts.add(dataFromForm);
contact adding is implemented by "Add" button. it is better not to mix this functionality

2020-03-09 07:56 UTC, Zwillinge commented on sources/views/contacts/listInContacts.js
> +			this.list.select(url[0].params.id);
what if a users write a non-existent id into the address bar?

2020-03-09 07:56 UTC, Zwillinge commented on sources/views/contacts/listInContacts.js
> +			this.list.select(this.list.getFirstId());
what if there are no contacts in the list?

2020-03-09 07:56 UTC, Zwillinge commented on sources/views/settings.js
> +					view: "segmented", localId: "language", value: "RU", inputWidth: 250, align: "center", options: [
value:"RU" is incorrect, you use "en" and "ru" locales in your app
however, do not harcode this value as it depends on the active locale. get it as `langs.getLang()`

2020-03-09 07:56 UTC, Zwillinge commented on sources/views/contacts/listInContacts.js
> +		this.app.callEvent("onChangeUrlInList", [itemById]);
the same url change happens in the form module, you can handle it there
and get item data from contact model directly

2020-03-09 07:57 UTC, Zwillinge commented
and please check data module for statuses and countries. there, if you press the remove button when no contact is selected, the application throws an error "non-existent id in remove command"

2020-03-09 12:11 UTC, Zwillinge commented on sources/views/contacts/listInContacts.js
> +			this.list.select(this.list.getFirstId());
you can check it by `.exists()` for both cases (it will return `false` if it cannot find the related item in the pull )

2020-03-09 12:11 UTC, Zwillinge commented on sources/views/contacts/listInContacts.js
> +		this.list.select(id);
add to first position or show item - with many contacts you will not see the newly added one

2020-03-09 12:11 UTC, Zwillinge commented on sources/views/contacts/formInContacts.js
> +		if(contacts.config.data.length){
you need to check it as `.exists()`  - it covers both cases when contact does not exist and there are no contacts

2020-03-09 12:11 UTC, Zwillinge commented on sources/views/settings.js
> +					view: "segmented", localId: "language", value: "RU", inputWidth: 250, align: "center", options: [
still, the initial value defined as `langs.getLang()` is needed

2020-03-09 19:55 UTC, Zwillinge commented on sources/views/contacts/listInContacts.js
> +		const lengthOfContacts = contacts.config.data.length;
do not check data by view.config. if you load data by url, load or sync, config.data will be empty. 
if you want to check whether the component has data, you can use `contacts.count()`

2020-03-09 20:25 UTC, notheheanymore approved these changes

2020-03-10 08:23 UTC, Zwillinge approved these changes

2020-03-10 08:23 UTC, merged